name: CI

on:
  push:
    paths:
      - '**.json'
      - '**.rb'
      - '**.py'
      - '.github/workflows/**.yml'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run a Python script
      run: |
        which python3
        python3 --version
        python3 hello.py
    - name: Run a Ruby script
      run: |
        which ruby
        ruby --version
        ruby hello.rb
    - name: Push file to GitHub Repo
      run: |
        /bin/date > file.txt
        /bin/date > environment.txt
        /usr/bin/env >> environment.txt
        git config --global user.email "ehom@acm.org"
        git config --global user.name "ehom"
        git add file.txt
        git add environment.txt
        git commit -m "updated file"
        git push
