name: CI

on:
  push:
    paths:
      - '**.json'
      - '.github/workflows/blank.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Pseudo-loc
      run: python --version
    - name: check in file
      run: |
        file.txt < date
        git add file.txt
        git commit -m "updated file"
        git push
